version: "3"

tasks:
  generate-rbs:
    cmds:
      - bundle exec rbs-inline --output .

  prototype-rbs:
    cmds:
      - rbs prototype rb {{ .CLI_ARGS}}

  type-check:
    cmds:
      - bundle exec steep check
