module RubyLsp
  module Support
    module Definitions
      class HandleSuperclass
        interface _ResponseBuilder
          def <<: (untyped) -> void

          def response: -> Array[untyped]
        end

        include Requests::Support::Common

        @response_builder: _ResponseBuilder
        @nesting: Array[String]
        @index: untyped
        @node: Prism::CallNode | Prism::ConstantPathNode

        def initialize: (Prism::CallNode | Prism::ConstantPathNode, Array[String], _ResponseBuilder, untyped) -> void

        def call: () -> void

        def handle_superclass_node: (String, Array[String]) -> void

        def on_superclass_call_node: (String, Array[String]) -> void

        private

        def build_location_link: (RubyIndexer::Entry::Class entry_class) -> untyped

        def resolve_superclass_node: (String, Array[String]) -> String

        def find_entry: (String? name, ?Array[String] nesting) -> RubyIndexer::Entry::Class?

        def search: (String name, ?Array[String] nesting) -> Array[RubyIndexer::Entry::Class | untyped]
      end
    end
  end
end
