module RubyLsp
  module Support
    class Addon
      @global_state: untyped

      @outgoing_queue: untyped

      def activate: (untyped global_state, untyped outgoing_queue) -> void

      def deactivate: -> void

      def name: () -> "ruby-lsp-support"

      def version: () -> "0.1.0"

      def create_definition_listener: (untyped response_builder, untyped _uri, RubyLsp::NodeContext node_context, untyped dispatcher) -> untyped
      def create_completion_listener: (untyped response_builder, untyped _uri, RubyLsp::NodeContext node_context, untyped dispatcher) -> untyped
      def create_hover_listener: (untyped response_builder, RubyLsp::NodeContext node_context, untyped dispatcher) -> untyped
    end
  end
end
