module RubyLsp
  module Support
    class Definition
      @response_builder: untyped

      @node_context: untyped

      #     Referring to superclass::FooInstance
      #     The value of @node_context.nesting will be
      #     ["Bar", "BarInstance", "CarInstance"]]
      #     class CarInstance < superclass::FooInstance
      #     end
      #   end
      # end
      @nesting: Array[String]

      @index: untyped

      def initialize: (untyped response_builder, NodeContext node_context, untyped index, untyped dispatcher) -> void

      def on_call_node_enter: (Prism::CallNode node) -> void

      def on_constant_path_node_enter: (Prism::ConstantPathNode node) -> void
    end
  end
end
