module RubyLsp
  module Support
    module Hovers
      class JumpToSpec
        @node: Prism::ConstantPathNode | Prism::ConstantReadNode

        @response_builder: untyped

        @node_context: NodeContext

        @spec_files: Array[String]

        @workspace_path: String

        @index: RubyIndexer::Index

        include Requests::Support::Common

        def initialize: (Prism::ConstantPathNode | Prism::ConstantReadNode node, untyped response_builder, NodeContext node_context, RubyIndexer::Index index, String workspace_path) -> void

        def call: () -> void

        def source_file: (RubyIndexer::Entry::Namespace) -> ("" | ::String)

        private

        def find_spec_entry: (RubyIndexer::Entry::Namespace) -> String?

        def spec_files: () -> Array[String]

        def full_name: (Prism::ConstantReadNode node) -> String

        def entry: (Prism::ConstantPathNode | Prism::ConstantReadNode node) -> RubyIndexer::Entry::Namespace?

        def get_guessed_spec_file: (String) -> String

      end
    end
  end
end
